spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    #url: jdbc:mysql://15.165.88.189:3306/norway_forest?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/norway_forest?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: prefAdmin
    #password: PrefServer@)20
    username: root
    password: 1111
    hikari:
      max-lifetime: 90000
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher